Crunch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace="account")),
    path('chat/',include('chat.urls',namespace="chat")),
    path('tinymce/',include('tinymce.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

from .views import ViewProfile,FollowInProfile,UpdateProfile,Library,search_feature_library,DeleteBlog_library,Forgot_password

app_name = "account"
urlpatterns = [
    path('login/',views.userLogin,name="userLogin"),
    path('profileview/<int:pk>/',ViewProfile.as_view(),name="ProfileView"),
    path('update-profile/<int:pk>/',UpdateProfile.as_view(),name="UpdateProfile"),
    path('follow-in-profile/<int:pk>/',FollowInProfile.as_view(),name="followInProfile"),
    path('signup/',views.userSignup,name="userSignup"),
    path('logout/',views.userLogout,name='userLogout'),

    path('library/',Library.as_view(),name="Library"),
    path('search-library/',search_feature_library,name='search_feature_library'),
    path('delete-blog/<int:pk>/',DeleteBlog_library.as_view(),name="DeleteBlog_library"),

    path('forgot-password/',Forgot_password.as_view(),name="Forgot_password"),
]

blog/urls.py
from django.urls import path

from blog.views import Home,CreateBlog,BlogDetail,UpdateBlog,Aboutpage,Contactpage,DeleteBlog,search_feature,like_post,DeleteComment,rateBlog,LinkContainer,NotificationView

app_name = "blog"
urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('create-blog/',CreateBlog.as_view(),name="create_blog"),
    path('like-post/<str:slug>/',like_post,name='like_post'),
    path('blog/<str:slug>/',BlogDetail,name="blog_detail"),
    path('update-blog/<str:slug>/',UpdateBlog.as_view(),name="update_blog"),
    path('search/',search_feature,name='search_feature'),
    path('delete-blog/<int:pk>/',DeleteBlog.as_view(),name="delete_blog"),
    path('about-us/',Aboutpage.as_view(),name='Aboutpage'),
    path('contact-us/',Contactpage.as_view(),name='Contactpage'),
    path('rate-blog/<str:slug>/',rateBlog,name="rateBlog"),
    path('save-link/<int:pk>/',LinkContainer,name="save_link"),

    path('notification/',NotificationView.as_view(),name='notification'),

    path('delete-comment/<int:pk>/',DeleteComment,name="DeleteComment"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.conf import settings


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


GENDER_CHOICE = (
    ('M','Male'),
    ('F','Female'),
    ('O','Others')
)

class User(AbstractUser):
    username = None
    email = models.EmailField(unique = True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()


class Profile(models.Model):
    avatar = models.ImageField(upload_to='profile',blank=True,null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profiles')
    address = models.CharField(max_length=255,blank=True,null=True)
    dob = models.DateField(blank=True,null=True)
    gender = models.CharField(choices=GENDER_CHOICE,max_length=128,blank=True,null=True)
    bio = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.user.email
    

class Follow(models.Model):
    youser = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name = 'account')
    follow = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_info')

    def __str__(self):
        return f"{self.youser.email} -> {self.follow.email}"

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User,Profile

class userSignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required. Enter a valid email address.')
    class Meta:
        model = User    
        fields = ['email','password1','password2']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        for i in self.fields:
            self.fields[i].widget.attrs.update({'class':'form-control'})
    

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    class Meta:
        model = Profile
        fields = ['avatar','first_name','last_name','address','dob','gender','bio']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        for i in self.fields:
            if i == 'dob':
                self.fields[i].widget.attrs.update({'placeholder':'yyyy-mm-dd'})
            self.fields[i].widget.attrs.update({'class':'form-control'})

account/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,get_user_model,logout,login
from django.views.generic import UpdateView
from django.contrib import messages
from django.views import View
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView,DeleteView
from django.db.models import Exists,Count,Subquery,OuterRef,Q
from taggit.models import Tag
from django.contrib.auth.models import User

from account.models import User,Profile,Follow
from blog.models import CreateBlogModel,Rating,BlogCommentModel,LinkContainerModel
from account.forms import userSignupForm,ProfileForm

activeUser = get_user_model()

def userLogin(request,**kwargs):
    print(kwargs.get('data'))
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request,email = email,password = password)
        if user:
            login(request,user)
            var = User.objects.get(email = request.user)
            if(var.first_name == '' and var.last_name == ''):
                messages.info(request,"you cannot post any blog without filling your details")
                try:
                    return redirect(reverse('account:UpdateProfile',args=(request.user.profiles.id,)))
                except:
                    return redirect('blog:home')
            else:
                messages.info(request,'logged in successfully')
                print('session',request.session.get('next'))
                if request.session.get('next'):
                    return redirect(reverse('blog:blog_detail',args=(request.session.get('next'),)))
                if request.session.get('next'):
                    del(request.session['next'])
                return redirect('blog:home')
        else:
            messages.info(request, "incorrect input")
    return render(request,'login.html')


class ViewProfile(View):

    def get(self, request, pk):
        profile_model = get_object_or_404(Profile, user_id=pk)
        user = User.objects.get(id = pk)
        initial_data = {
            'first_name': user.first_name,
            'last_name': user.last_name,
        }
        form = ProfileForm(instance=profile_model,initial = initial_data)

        following =[i.follow for i in Follow.objects.filter(youser = User.objects.get(id = pk))]
        follower =[i.youser for i in Follow.objects.all() if i.follow == User.objects.get(id = pk)]
        following_bool = True if self.request.user in follower else False
        total_likes = sum([len(i.blog_like.all()) for i in CreateBlogModel.objects.filter(user__id = pk)])
        total_contents = CreateBlogModel.objects.filter(user__id = pk)
        my_blog = CreateBlogModel.objects.filter(user__id = pk,status = 'public')
        total_rating = 0
        for i in my_blog:
            total_rating = total_rating + sum([j.rate for j in Rating.objects.filter(blog = i)])

        total_comments = BlogCommentModel.objects.filter(user = user).count()

        context = {
            'profile_model': profile_model,
            'form': form,
            'CreateBlogModel':CreateBlogModel.objects.filter(user__id = pk,status = 'public'),
            'following':following,
            'follower':follower,
            'total_likes':total_likes,
            'total_contents':total_contents,
            'total_rating':total_rating,
            'total_comments':total_comments,
            'following_bool':following_bool,
            }
        return render(request, 'profile.html', context)


class UpdateProfile(UpdateView):
    model = Profile
    form_class=ProfileForm
    template_name = 'update_profile.html'
    # success_url = reverse_lazy('account:ProfileView',kwargs={'pk':object.pk})
    
    def get_initial(self):
        initial_data =  super().get_initial()
        initial_data = {
            'first_name':self.request.user.first_name,
            'last_name':self.request.user.last_name,
        }
        return initial_data
    
    def get_success_url(self):
        return reverse('account:ProfileView',args=(self.object.user.pk,))
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.request.user.first_name = form.cleaned_data['first_name']
        self.request.user.last_name = form.cleaned_data['last_name']
        self.request.user.save()
        messages.success(self.request, "Profile details updated.")
        return super().form_valid(form)

class FollowInProfile(View):
    def get(self,request,pk):
        get,create = Follow.objects.get_or_create(youser = self.request.user,follow = User.objects.get(id = pk))
        if not create:
            if get:
                get.delete()
            else:
                return redirect(reverse('account:ProfileView',args=(pk,)))

        return redirect(reverse('account:ProfileView',args=(pk,)))           


def userSignup(request):
    form = userSignupForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        Profile.objects.create(user = user)
        return redirect('account:userLogin')
    print(request.POST.get('email'))
    return render(request,'signup.html',context={'form':form})


def userLogout(request):
    logout(request)
    messages.info(request,'logged out successfully')
    return redirect('blog:home')


class Library(View):
    def get(self,request):
        user_blog = CreateBlogModel.objects.filter(user = request.user)
        
        saved_blog = CreateBlogModel.objects.annotate(has_link = Exists(LinkContainerModel.objects.filter(blog__id = OuterRef('pk'),user = request.user))).filter(has_link = True)
        
        context = {
            'user_blog':user_blog,
            'saved_blog':saved_blog,
        }
        return render(request,'library.html',context)



def search_feature_library(request):
    if request.method == 'POST':
        search_query = request.POST.get('search')
        blog_model = CreateBlogModel.objects.filter(user = request.user,title__icontains=search_query,tags__name__icontains=search_query)
        print(blog_model)
        context = {
            'query':search_query,
            'searched':blog_model,
            # 'tag_search':CreateBlogModel.objects.filter(tags = Tag.objects.get(name = search_query)),
        }
        return render(request,'library.html',context)
    return render(request,'library.html')


@method_decorator(login_required,name='dispatch')
class DeleteBlog_library(DeleteView):
    model = CreateBlogModel
    success_url = reverse_lazy('account:Library')
    template_name = 'read_blog.html'


class Forgot_password(View):
    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')
        verify_email = None
        try:
            verify_email = User.objects.get(email = email)
        except:
            verify_email = None

        if verify_email != None and password == confirm_password:
            verify_email.set_password(confirm_password)
            verify_email.save()
            print('saved')
            return redirect('account:userLogin')
            
        return render(request,'fpassword.html')

    def get(self, request):
        return render(request,'fpassword.html')

account/templates/fpassword.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6"> <!-- Adjusted column classes -->
            <div class="card shadow-sm">
                <div class="card-header">
                    <h3>Verify your email</h3>
                </div>
                <div class="card-body">
                    <form method="post" id="verify_form">
                        {% csrf_token%}
                        <div class="form-group">
                          <label>Email</label>
                          <input type="text" class="form-control" placeholder="Email" name="email">
                        </div>
                        <div class="form-group">
                          <label>New password</label>
                          <input type="password" class="form-control" placeholder="New password" name="new_password">
                        </div>
                        <div class="form-group">
                          <label>Confirm password</label>
                          <input type="password" class="form-control" placeholder="Confirm password" name="confirm_password">
                        </div>
                        <input class="btn btn-primary btn-sm" type="submit" value="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
</script>
{% endblock %}

account/templates/library.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .card{
            background-color: #F7F9F9;
            transition: 250ms;
          }
        .card:hover{
            box-shadow:2px 2px 10px 5px rgb(203, 203, 203);
          }
        .saved{
          padding:1rem;
          border-radius:5px;
          height:70vh;
        }
        .saved ol{
          padding-left:2rem;
          margin:0px;
        }
        .blog_title{
          color:black;
          text-decoration:none;
        }
        .blog_title:hover{
          color:black;
          text-decoration:underline;
        }
    </style>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                  <div class="saved border">
                    <h5 class="read_later pt-2">Read later</h5><hr>
                    <ol>
                      {% for i in saved_blog %}
                      <li><a class="blog_title" href="{% url 'blog:blog_detail' i.slug %}">{{i.title}}</a></li>
                      {% endfor %}
                    </ol>
                  </div>
                </div>
                <div class="col-lg-9">
                    <h4><a class="text-dark" href="{% url 'account:Library' %}">Library</a></h4>

                    <form method="post" action="{% url 'account:search_feature_library' %}">
                        {% csrf_token %}
                        <div class="input-group mb-3 search-bar">
                          <input type="text" class="form-control" placeholder="search..." aria-label="Recipient's username" name="search" aria-describedby="inputGroup-sizing-lg">
                          <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                          </div>
                        </div>
                    </form>

                    {% if query %}
                        {% if searched %}
                        {% for i in searched %}
                        <div id="content_{{ i.id }}" class="card mt-4">
                            <div class="card-header d-flex justify-content-between">
                              <div>
                                <a class="blog_title" href="{% url 'blog:blog_detail' i.slug %}">{{ i.title }}</a>
                              </div>
                              <div class="dropdown">
                                <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton_{{ i.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <i class="fas fa-ellipsis-v"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right bg-white" aria-labelledby="dropdownMenuButton_{{ i.id }}">
                                  <a class="dropdown-item" href="{% url 'blog:update_blog' i.slug %}">Edit</a>
                                  <a class="dropdown-item text-danger" data-toggle="modal" data-target="#exampleModal_delete" href="{% url 'blog:delete_blog' i.id %}">Delete</a>
                                </div>
                              </div>
                            </div>
                            <div class="card-body py-0 px-2">
                              <div class="row">
                                <div class="col">
                                  <blockquote class="blockquote mb-0">
                                    <p><small>{{ i.content|striptags|slice:":200"|lower|safe }}...</small></p>
                                    <footer class="blockquote-footer">{{ i.user.first_name }}&nbsp;&nbsp;<cite title="Source title">{{ i.created_at }}</cite></footer>
                                  </blockquote>
                                </div>
                                <div class="col-auto">
                                  {% if i.image %}
                                    <img src="{{ i.image.url }}" width="100px" height="100px" alt="Image" class="img-fluid m-3">
                                  {% else %}
                                    <img src="https://hips.hearstapps.com/hmg-prod/images/blue-lake-water-with-waves-background-royalty-free-image-1701283846.jpg?crop=0.66667xw:1xh;center,top&resize=1200:*" width="100px" height="100px" alt="Image" class="img-fluid m-3">
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                          </div>
                          
                        {% endfor %}
                        {% endif %}
                    {% endif %}

                    {% for b in user_blog %}
                        <div>
                            <div id="content_{{ b.id }}" class="card mt-4">
                                <div class="card-header d-flex justify-content-between">
                                  <div>
                                    <a class="blog_title" href="{% if b.status == 'public' %}{% url 'blog:blog_detail' b.slug %} {% else %} {% url 'blog:update_blog' b.slug %} {% endif %}">{{ b.title }}</a>&nbsp;&nbsp;&nbsp;
                                    {% if b.status == 'draft' %}<span class="badge badge-warning">DRAFT</span>{% endif %}
                                  </div>
                                  <div class="dropdown">
                                    <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton_{{ b.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="fas fa-ellipsis-v"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right bg-white" aria-labelledby="dropdownMenuButton_{{ b.id }}">
                                      <a class="dropdown-item" href="{% url 'blog:update_blog' b.slug %}">Edit</a>
                                      <a id="blog" class="dropdown-item text-danger" data-toggle="modal" data-target="#exampleModal_delete" data-blog-id={{b.id}}>Delete</a>
                                    </div>
                                  </div>
                                </div>
                                <div class="card-body py-0 px-2">
                                  <div class="row">
                                    <div class="col">
                                      <blockquote class="blockquote mb-0">
                                        <p><small>{{ b.content|striptags|slice:":200"|lower|safe }}...</small></p>
                                        <footer class="blockquote-footer">{{ b.user.first_name }}&nbsp;&nbsp;<cite title="Source title">{{ b.created_at }}</cite></footer>
                                      </blockquote>
                                    </div>
                                    <div class="col-auto">
                                      {% if b.image %}
                                        <img src="{{ b.image.url }}" width="100px" height="100px" alt="Image" class="img-fluid m-3">
                                      {% else %}
                                        <img src="https://hips.hearstapps.com/hmg-prod/images/blue-lake-water-with-waves-background-royalty-free-image-1701283846.jpg?crop=0.66667xw:1xh;center,top&resize=1200:*" width="100px" height="100px" alt="Image" class="img-fluid m-3">
                                      {% endif %}
                                    </div>
                                  </div>
                                </div>
                              </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>



  <div class="modal fade" id="exampleModal_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form id="delete_blog" method="post">
            {% csrf_token %}
            <!-- <button type="submit" data-blog-id="{{blog_model}}" class="btn btn-danger">delete</button> -->
            <button type="submit" class="btn btn-danger">delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded",()=>{
        var blog_id_selector = document.getElementById('blog');
        var blog_id = document.getElementById('blog').dataset.blogId;
        blog_id_selector.addEventListener("click",()=>{
            console.log('/delete-blog/'+blog_id+'/');
            delete_modal = document.getElementById('delete_blog').setAttribute('action','/delete-blog/'+blog_id+'/');
        })
    })
  </script>
{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% block content %}


<style>
    #countdownAlert{
        cursor: pointer;
    }
</style>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" id="countdownAlert" role="alert">
                {{message}}<span id="countdown"> 2</span>
            </div> 
        {% endfor %}
    {% endif %}
    <div class="container mt-5">
        <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
            <div class="card-header">
                <h3 class="text-center">Login</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                <div class="form-group">
                    <label for="username">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" autofocus>
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" autofocus>
                </div>
                <button type="submit" class="btn btn-primary btn-block"><a href="/{{path}}" class="text-light">Login</a></button>
                </form>
                <div class="text-center mt-3">
                <a href="{% url 'account:Forgot_password' %}">Forgot Password?</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <script>
        let countdownAlert = document.getElementById('countdownAlert');
        countdownAlert.addEventListener('click',()=>{
            countdownAlert.remove();
            clearInterval(countdownInterval);
        })

        let countdown = 2;

        let countdownInterval = setInterval(print,1000);

        function print(){
            countdown--;
            document.getElementById('countdown').textContent = " " + countdown;
            console.log(countdown);
            if(countdown <= 0){
                clearInterval(countdownInterval);
                countdownAlert.remove();
            }
        }

    </script>
{% endblock %}

account/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h3 class="text-center">Sign Up</h3>
            </div>
            <div class="card-body">
              <form method="POST">
                {% csrf_token %}
                <!-- <div class="form-group">
                  <label for="email">Email:</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="Enter your email">
                </div>
                <div class="form-group">
                  <label for="password">Password:</label>
                  <input type="password" class="form-control" name="password1" id="password" placeholder="Enter your password">
                </div>
                <div class="form-group">
                  <label for="confirm_password">confirm password:</label>
                  <input type="password" class="form-control" name="password2" id="confirm_password" placeholder="Enter your password">
                </div> -->

                {{ form.as_p }}
                <button type="submit" class="btn btn-success btn-block">Sign Up</button>
              </form>
              <div class="text-center mt-3">
                <a href="{% url 'account:userLogin' %}">Already have an account? Login</a>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

account/templates/update_profile.html
{% extends 'base.html' %}
{% block content %}
{% if messages %}
<div class="alert alert-warning" role="alert">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
<div id="second">
    <form method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="submit" class="btn btn-sm btn-primary">
      <a class="btn btn-primary btn-sm" href="{% url 'account:userLogin' %}">change password</a>
    </form>
  </div>
{% endblock %}