Crunch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('account/',include('account.urls',namespace="account")),
    path('chat/',include('chat.urls',namespace="chat")),
    path('tinymce/',include('tinymce.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

from .views import ViewProfile,FollowInProfile,UpdateProfile,Library,search_feature_library,DeleteBlog_library,Forgot_password

app_name = "account"
urlpatterns = [
    path('login/',views.userLogin,name="userLogin"),
    path('profileview/<int:pk>/',ViewProfile.as_view(),name="ProfileView"),
    path('update-profile/<int:pk>/',UpdateProfile.as_view(),name="UpdateProfile"),
    path('follow-in-profile/<int:pk>/',FollowInProfile.as_view(),name="followInProfile"),
    path('signup/',views.userSignup,name="userSignup"),
    path('logout/',views.userLogout,name='userLogout'),

    path('library/',Library.as_view(),name="Library"),
    path('search-library/',search_feature_library,name='search_feature_library'),
    path('delete-blog/<int:pk>/',DeleteBlog_library.as_view(),name="DeleteBlog_library"),

    path('forgot-password/',Forgot_password.as_view(),name="Forgot_password"),
]

blog/urls.py
from django.urls import path

from blog.views import Home,CreateBlog,BlogDetail,UpdateBlog,Aboutpage,Contactpage,DeleteBlog,search_feature,like_post,DeleteComment,rateBlog,LinkContainer,NotificationView

app_name = "blog"
urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('create-blog/',CreateBlog.as_view(),name="create_blog"),
    path('like-post/<str:slug>/',like_post,name='like_post'),
    path('blog/<str:slug>/',BlogDetail,name="blog_detail"),
    path('update-blog/<str:slug>/',UpdateBlog.as_view(),name="update_blog"),
    path('search/',search_feature,name='search_feature'),
    path('delete-blog/<int:pk>/',DeleteBlog.as_view(),name="delete_blog"),
    path('about-us/',Aboutpage.as_view(),name='Aboutpage'),
    path('contact-us/',Contactpage.as_view(),name='Contactpage'),
    path('rate-blog/<str:slug>/',rateBlog,name="rateBlog"),
    path('save-link/<int:pk>/',LinkContainer,name="save_link"),

    path('notification/',NotificationView.as_view(),name='notification'),

    path('delete-comment/<int:pk>/',DeleteComment,name="DeleteComment"),
]

chat/urls.py
from django.urls import path

from chat.views import ChatView,MessageView

app_name = "chat"
urlpatterns = [
    path('',ChatView.as_view(),name="chatview"),
    path('<int:userid>/',MessageView.as_view(),name="MessageView"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crunch Blog</title>
    {% block stylesheet %}
        <script src="https://kit.fontawesome.com/42d3849b04.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'js/tinymce.min.js' %}">
        <!-- <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}"> -->

        
        <!-- <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
            <link rel="stylesheet" href="{% static 'js/jquery.min.js' %}">
            <link rel="stylesheet" href="{% static 'js/popper.min.js' %}"> -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
            <!-- <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script> -->

            
        <!-- <script src="https://cdn.tiny.cloud/1/seq26p9d00odqqdjovphd4yesq3avdmgpjdip3y3x83058gv/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script> -->
    {% endblock %}

    
    <style>
		html{
			height: 100%;
			box-sizing: border-box;
		}
		body{
			position: relative;
			margin: 0;
			min-height: 100%;
			padding-bottom: 400px;
			box-sizing: inherit;
            backgorund-color:#e6e6e6;
		}
        .body-container{
			min-height: 80vh;
		}

        /* footer */
        .p-1 div ul li a{
            color: #BBBBBB;
            text-decoration: none;
        }
        .p-1 div ul{
            padding: 0;
            margin: 0;
        }
        .p-1 div ul li{
            list-style: none;
        }
        .p-1 div ul li a:hover{
            color:#ECECEC;
        }
        .info li a:hover{
            color: #BBBBBB;
            cursor: auto;
        }
        .info li div a{
            padding: 5px;
        }
        .info li div a i:hover{
            cursor: pointer;
        }
        .footer{
            position: absolute;
            left: 0;
            right: 0;
            bottom: 0;
        }
    </style>

</head>
<body>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
    {% block notification %}
        {% include 'notification.html' %}
    {% endblock %}
    <div class="container body-container">
        {% block content %}
        {% endblock %}
    </div>
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}

</body>
</html>

templates/footer.html
<div class="footer bg-dark text-light">
	<div class="container">
		<div class="d-flex justify-content-between p-3">
			<div class="p-1">
				<div>
					<p class="fs-6">Employers</p><hr>
					<ul>
						<li><a href="{% url 'account:userSignup' %}">Register</a></li>
						<li><a href="{% url 'blog:Contactpage' %}">Contact Us</a></li>
					</ul>
				</div>
			</div>
			<div class="p-1">
				<div>
					<p class="fs-6">Readers</p><hr>
					<ul>
						<li><a href="{% url 'account:userSignup' %}">Register</a></li>
						<li><a href="{% url 'account:userLogin' %}">Login</a></li>
						<li><a href="">Search article</a></li>
					</ul>
				</div>
			</div>
			<div class="p-1">
				<div>
					<p class="fs-6">Links</p><hr>
					<ul>
						<li><a href="{% url 'blog:home' %}">Blog</a></li>
						<li><a href="{% url 'blog:Contactpage' %}">Contact Us</a></li>
						<li><a href="{% url 'blog:Aboutpage' %}">About Us</a></li>
					</ul>
				</div>
			</div>
			<div class="p-1">
				<div>
					<p class="fs-5">Crunch</p><hr>
					<ul class="info">
						<li><a href="{% url 'blog:home' %}">Crunch</a></li>
						<li><a href="#">Address</a></li>
						<li><a href="#">Phone no</a></li>
						<li><a href="#">info@Crunch.com</a></li>
						<li>
							<div class="d-flex flex-row mb-3">
								<a href="#"><i class="fa-brands fa-facebook"></i></a>
								<a href="#"><i class="fa-brands fa-instagram"></i></a>
								<a href="#"><i class="fa-brands fa-youtube"></i></a>
								<a href="#"><i class="fa-brands fa-x-twitter"></i></a>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
        <div class="text-center py-3">
            <p class="fs-6">Copyright © 2024 Crunch Blog. All rights reserved.</p>
        </div>
	</div>
</div>

templates/navbar.html
<style>
  {% comment %} .navbar{
    background-color: #D0D3D4;
  }
  .navbar a{
    color:#092635;
  }
  .navbar-nav{
    background-color: #D0D3D4;
  }
  .navbar_brand{
    font-size: 2rem;
  }
  .dropdown-menu{
    background-color: #D0D3D4;
  } 
  
  .navbar-toggler-icon{
    color:black;
    background-color: black;
  }{% endcomment %}

/* Add underline effect to the active tab */
{% comment %} .navbar-nav .nav-item.active a {
  border-bottom: 2px solid #007bff; /* Adjust the color as needed */
} {% endcomment %}

</style>

<nav class="navbar navbar-expand-lg mb-3 navbar-light bg-light">
  <div class="container">
    <!-- Brand/logo -->
    <a class="navbar-brand p-2 navbar_brand" href="{% url 'blog:home' %}">Crunch Blog</a>
	{{notification}}

    <!-- Burger button for mobile devices -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon text-dark"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Left-aligned links -->
      <ul class="navbar-nav">
        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
          <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
        </li> 
        <li class="nav-item {% if request.path == '/about-us/' %}active{% endif %}">
          <a class="nav-link" href="{% url 'blog:Aboutpage' %}">About Us</a>
        </li>
        <li class="nav-item {% if request.path == '/contact-us/' %}active{% endif %}">
          <a class="nav-link" href="{% url 'blog:Contactpage' %}">Contact Us</a>
        </li>
      </ul>

      <!-- Right-aligned links and dropdown -->
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == '/create-blog/' %}active{% endif %}">
          <a class="nav-link" href="{% url 'blog:create_blog' %}">write</a>
        </li>
        <li class="nav-item">
	  <a class="nav-link" id="bell" href="{% url 'blog:notification' %}"><i id="bell_ring" class="fa-regular fa-bell fa-lg" data-toggle="modal" data-target="#exampleModalScrollable"></i><span class="badge badge-light"></span></a>
        </li>
        <li class="nav-item {% if request.path == '/create-blog/' %}active{% endif %}">
          <a class="nav-link" href="{% url 'chat:chatview' %}"><i class="fa-regular fa-message fa-lg"></i></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if request.path == '/account/profileview/2/' %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.email}}</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'account:ProfileView' request.user.id %}">Profile</a>
            <a class="dropdown-item" href="{% url 'account:Library' %}">Library</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'account:userLogout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <a class="nav-link {% if request.path == '/login/' %}active{% endif %}" href="{% url 'account:userLogin' %}">Login</a>
        <a class="nav-link {% if request.path == '/signup/' %}active{% endif %}" href="{% url 'account:userSignup' %}">Signup</a>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded',function(){
      fetch('{% url "blog:notification" %}')
      .then(response => response.json())
      .then(data =>{
        var j = JSON.parse(data);
        for(let i of j){
          if (i.fields.viewed_status === false){
            document.querySelector('#bell_ring').setAttribute('class','fa-regular fa-bell fa-lg fa-shake')
            document.querySelector('.badge').textContent = j.length
          }
        }
      })
  })
</script>

templates/notification.html
<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalScrollable">
  Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Notification</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group list-group-flush">
        </ul>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
  var list_group = document.querySelector('.list-group');
  document.addEventListener('DOMContentLoaded',function(){
    document.getElementById('bell').addEventListener('click',(e)=>{
      if(e){
        e.preventDefault();
      }

      fetch('{% url "blog:notification" %}')
      .then(response => response.json())
      .then(data =>{
        var j = JSON.parse(data);
        for(let i of j){
          if (i.fields.viewed_status == false){
            const new_a_tag = document.createElement('a')
            new_a_tag.setAttribute('class','list-group-item list-group-item-action');
            new_a_tag.setAttribute('id',i.pk)
            new_a_tag.setAttribute('href','/blog/'+i.fields.slug+'/')
            new_a_tag.textContent = i.fields.fields;
            new_a_tag.addEventListener("click",function(event){
              event.preventDefault()

              sendNotification(i.pk);
              window.location.href='/blog/'+i.fields.slug+'/'
            });
            list_group.append(new_a_tag);
          }
        }
      })
      list_group.textContent = '';
    })
  })


  function sendNotification(id){
    fetch('{% url "blog:notification" %}',{
      method:'POST',
      headers:{
        'Content-Type':'application/json',
        'X-CSRFToken': getCookie('csrftoken')
      },
      body:JSON.stringify({'status':id})
    })
    .then(response => response.json)
    .then(data => console.log(id))
  }

    // Function to get CSRF token from cookies
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
</script>